%plot the results generated by the script DiminishingOverlapAnalysis.m
%Written by Min Chen (minchen1@upenn.edu)

%             saveAll_new{f}{1,k,counter}=relativeTransform;
%             saveAll_new{f}{2,k,counter}=numOkMatches;
%             saveAll_new{f}{3,k,counter}=numMatches;
%             saveAll_new{f}{4,k,counter}=pixelColLeft;
%             saveAll_new{f}{5,k,counter}=colscropped;

for w=1:3 %3 groups, HC, CSCR, RP
    
    switch w
        case 1
            range = 5:20;
        case 2
            range = 1:4;
        case 3
            range = 21:22;
    end
    
    N = size(range,2);
    
    numOkMatches=zeros(N,55);
    pixelColLeft=zeros(N,55);
    numMatches=zeros(N,55);
    
    figure(w)
 %   hold on
    y_all = [];
    for j=1:4 %4 types in order: confocal, split, DF and Multimodal(all 3)
        
        counter = 0
        for i=range%1:22
            counter = counter +1;
            k=[saveAll_new{i+2}{4,j,:}];
            Istart=find(k==300); %find index where it's 300 pixels out
            k=[saveAll_new{i+2}{4,j,Istart:end}];
            pixelColLeft(counter,:) = padarray(k',55-size(k,2),0,'post');
            k=[saveAll_new{i+2}{2,j,Istart:end}];
            numOkMatches(counter,:) = padarray(k',55-size(k,2),0,'post');
            k=[saveAll_new{i+2}{3,j,Istart:end}];
            numMatches(counter,:) = padarray(k',55-size(k,2),0,'post');
            
        end
        
        %Find those that meet the condition.
        x=max(pixelColLeft,[],1);
        y=mean(numOkMatches > 10 | ((numOkMatches./numMatches) > .5 & numOkMatches > 1));
        y_all=[y_all y'];
    end
    
    plot(x,y_all)
    if(w==1)
        legend('Confocal','SD','DF','All Modalities')
    end
    xlabel('Columns of Pixels in Overlapping Region') 
    ylabel('Accuracy') 
    
%    hold off
end