function [  ] = addToSelection( name )
% Robert Cooper 10-17-2014
%   This script interacts with photoshop to add the input name to the
%   selection.


script = [ 'var re = "' name '";'...
'    var matches = collectNamesAM(re);  '...
'    for( var l = 0; l < matches.length; l++ ){  '...
'        addToSelectionByIndex( matches[l], false );  '...
'    }'...
''...      
'    function collectNamesAM(re){  '...
'       var allLayers = new Array();  '...
'       var startLoop = Number( !hasBackground() );  '...
'       var endLoop = getNumberOfLayer();   '...
'       for( var l = startLoop;l <= endLoop; l++){  '...
'            while( !isValidActiveLayer( l ) ) {  '...
'                l++;  '...
'            }  '...
'            if( getLayerNameByIndex( l ).match(re) != null){ '... 
'                allLayers.push( l );  '...
'            }  '...
'        }  '...
'         return allLayers;  '...
'    };'...
'    function getActiveLayerIndex() {  '...
'         var ref = new ActionReference();  '...
'         ref.putProperty( 1349677170 , 1232366921 );  '...
'         ref.putEnumerated( 1283027488, 1332896878, 1416783732 );  '...
'         var res = executeActionGet(ref).getInteger( 1232366921 ) - Number( hasBackground() );  '...
'         res == 4 ? res++:res;  '...
'         return res;     '...
'    }'...
''...
'    function isValidActiveLayer( idx ) {  '...
'         var propName = stringIDToTypeID( "layerSection" ); '... 
'         var ref = new ActionReference();   '...
'         ref.putProperty( 1349677170 , propName);'...
'         '... 
'         ref.putIndex( 1283027488, idx );  '...
'         var desc =  executeActionGet( ref );  '...
'         var type = desc.getEnumerationValue( propName );  '...
'         var res = typeIDToStringID( type );   '...
'         return res == "layerSectionEnd" ? false:true;  '...
'    };'...
''...
'   function hasBackground() {'...
'       var ref = new ActionReference();'...
'       ref.putProperty( charIDToTypeID("Prpr"), charIDToTypeID( "Bckg" ));'...
'       ref.putEnumerated(charIDToTypeID( "Lyr " ),charIDToTypeID( "Ordn" ),charIDToTypeID( "Back" ));'...
'       var desc =  executeActionGet(ref);'...
'       var res = desc.getBoolean(charIDToTypeID( "Bckg" ));'...
'       return res; '...
'    };'...
''...
'    function addToSelectionByIndex( idx, forceVisible ){  '...
'         try{  '...
'           var idslct = charIDToTypeID( "slct" );'...
'           var desc5 = new ActionDescriptor();'...
'           var idnull = charIDToTypeID( "null" );'...
'           var ref1 = new ActionReference();'...
'           var idLyr = charIDToTypeID( "Lyr " );'...
'           ref1.putIndex( idLyr, idx );'...
'           desc5.putReference( idnull, ref1 );'...
'           var idselectionModifier = stringIDToTypeID( "selectionModifier" );'...
'           var idselectionModifierType = stringIDToTypeID( "selectionModifierType" );'...
'           var idaddToSelection = stringIDToTypeID( "addToSelection" );'...
'           desc5.putEnumerated( idselectionModifier, idselectionModifierType, idaddToSelection );'...
'           var idMkVs = charIDToTypeID( "MkVs" );'...
'           desc5.putBoolean( idMkVs, false );'...
'           executeAction( idslct, desc5, DialogModes.NO );  '...
'         }catch(e){ return -1; }  '...
'    };'...
''...
'    function getNumberOfLayer(){   '...
'    var ref = new ActionReference();   '...
'    ref.putEnumerated( charIDToTypeID("Dcmn"), charIDToTypeID("Ordn"), charIDToTypeID("Trgt") );   '...
'    var desc = executeActionGet(ref);   '...
'    var numberOfLayer = desc.getInteger(charIDToTypeID("NmbL"));   '...
'    return numberOfLayer;   '...
'    }; '...
''...
'    function getLayerNameByIndex( idx ) {   '...
'        var ref = new ActionReference();   '...
'        ref.putProperty( charIDToTypeID("Prpr") , charIDToTypeID( "Nm  " ));   '...
'        ref.putIndex( charIDToTypeID( "Lyr " ), idx );  '...
'        return executeActionGet(ref).getString(charIDToTypeID( "Nm  " ));   '...
'    }; ' ];

psjavascript(script);

end

