function [  ] = linkSelectedLayers( )
% Robert F Cooper 10-17-2014
%   This function links any selected layers together.

script = ['var idlinkSelectedLayers = stringIDToTypeID( "linkSelectedLayers" );'...
'    var desc7 = new ActionDescriptor();'...
'    var idnull = charIDToTypeID( "null" );'...
'        var ref3 = new ActionReference();'...
'        var idLyr = charIDToTypeID( "Lyr " );'...
'        var idOrdn = charIDToTypeID( "Ordn" );'...
'        var idTrgt = charIDToTypeID( "Trgt" );'...
'        ref3.putEnumerated( idLyr, idOrdn, idTrgt );'...
'    desc7.putReference( idnull, ref3 );'...
'executeAction( idlinkSelectedLayers, desc7, DialogModes.NO );' ];

psjavascript(script);

end

