function [ ] = make_Photoshop_group( name )
% Robert F Cooper 10-21-2014
%   This script makes a group.

script = ['var idMk = charIDToTypeID( "Mk  " );'...
'    var desc22 = new ActionDescriptor();'...
'    var idnull = charIDToTypeID( "null" );'...
'        var ref8 = new ActionReference();'...
'        var idlayerSection = stringIDToTypeID( "layerSection" );'...
'        ref8.putClass( idlayerSection );'...
'    desc22.putReference( idnull, ref8 );'...
'executeAction( idMk, desc22, DialogModes.NO );'...
''...
'var idsetd = charIDToTypeID( "setd" );'...
'    var desc23 = new ActionDescriptor();'...
'    var idnull = charIDToTypeID( "null" );'...
'        var ref9 = new ActionReference();'...
'        var idLyr = charIDToTypeID( "Lyr " );'...
'        var idOrdn = charIDToTypeID( "Ordn" );'...
'        var idTrgt = charIDToTypeID( "Trgt" );'...
'        ref9.putEnumerated( idLyr, idOrdn, idTrgt );'...
'    desc23.putReference( idnull, ref9 );'...
'    var idT = charIDToTypeID( "T   " );'...
'        var desc24 = new ActionDescriptor();'...
'        var idNm = charIDToTypeID( "Nm  " );'...
'        desc24.putString( idNm, """' name '""" );'...
'    var idLyr = charIDToTypeID( "Lyr " );'...
'    desc23.putObject( idT, idLyr, desc24 );'...
'executeAction( idsetd, desc23, DialogModes.NO );' ];

psjavascript(script);

end

