%% AOAutomontagingToolboxRegistryConfig
%
% Declare the toolboxes we need for the AOMontaging project and
% write them into a JSON file.  This will let us use the ToolboxToolbox to
% deliver unto us the perfect runtime environment for this project.

% Clear
clear;

%% Declare some toolboxes we want.
%
% Declare some Mathworks toolboxes that we are pretty sure we need.
config = [ ...
    tbToolboxRecord( ...
    'type', 'installed', ...
    'name', 'signal'), ...
    tbToolboxRecord( ...
    'type', 'installed', ...
    'name', 'stats'), ...
    tbToolboxRecord( ...
    'type', 'installed', ...
    'name', 'images'), ...
    tbToolboxRecord( ...
    'type', 'installed', ...
    'name', 'optim') ...
    
    % This is here as a template for how to specify a toolbox that will be
    % pulled down from gitHub.
    %
    % tbToolboxRecord( ...
    % 'type', 'git', ...
    % 'name', 'BrainardLabToolbox', ...
    % 'url', 'https://github.com:DavidBrainard/BrainardLabToolbox.git'), ... 
];

%% Write the config to a JSON file.
configPath = 'AOAutomontaging.json';
tbWriteConfig(config, 'configPath', configPath);

